### ISSUE TITLE
这是爆内存了吗

### ISSUE THREAD

**Issue by 111496583yzy** [smthemex/ComfyUI_TRELLIS#14]
got prompt
2024-12-27 11:44:30.874116158 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 140450031544320

!!! Exception during processing !!! [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 140450031544320

Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/execution.py", line 353, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 223, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 194, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/autodl-tmp/ComfyUI/execution.py", line 183, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/TRELLIS_node.py", line 114, in sampler_main
glb=image_to_3d(model,img,preprocess_image,covert2video,trial_id,seed,cfg,steps,slat_cfg,slat_steps,mesh_simplify,texture_size,mode,is_multiimage,gaussians2ply,multiimage_algo)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/app.py", line 28, in image_to_3d
outputs = pipeline.run(
File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 289, in run
image = self.preprocess_image(image)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 111, in preprocess_image
output = rembg.remove(input, session=self.rembg_session)
File "/root/miniconda3/lib/python3.10/site-packages/rembg/bg.py", line 266, in remove
masks = session.predict(img, *args, **kwargs)
File "/root/miniconda3/lib/python3.10/site-packages/rembg/sessions/u2net.py", line 29, in predict
ort_outs = self.inner_session.run(
File "/root/miniconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 266, in run
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 140450031544320

Prompt executed in 0.19 seconds

**Comment by smthemex** [comment]
配置onnxruntime-pgu

**Comment by 111496583yzy** [comment]
> 配置 onnxruntime-gpu
9824a29c71用这个版本能跑出来
