### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 155: invalid continuation byte

### ISSUE THREAD

**Issue by green21st** [smthemex/ComfyUI_TRELLIS#15]
i got this error while loading the model, help please!
[1/39] [MSVC][c++/pch]D:\ComfyUI-aki-v1.2\python\Lib\site-packages\cumm\build\core_cc\include\csrc\arrayref\ArrayPtr.h.pch|D:\ComfyUI-aki-v1.2\python\Lib\site-packages\cumm\build\core_cc\msvc_stub\include\csrc\arrayref\ArrayPtr.h.cc.o
FAILED: D:/ComfyUI-aki-v1.2/python/Lib/site-packages/cumm/build/core_cc/msvc_stub/include/csrc/arrayref/ArrayPtr.h.cc.o
!!! Exception during processing !!! 'utf-8' codec can't decode byte 0xd2 in position 155: invalid continuation byte
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\TRELLIS_node.py", line 62, in main_loader
    model=TrellisImageTo3DPipeline.from_pretrained(repo)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 60, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\base.py", line 39, in from_pretrained
    _models = {
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\base.py", line 40, in <dictcomp>
    k: models.from_pretrained(f"{path}/{v}")
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\models\__init__.py", line 60, in from_pretrained
    model = __getattr__(config['name'])(**config['args'], **kwargs)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\models\structured_latent_vae\decoder_mesh.py", line 108, in __init__
    SparseSubdivideBlock3d(
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\models\structured_latent_vae\decoder_mesh.py", line 43, in __init__
    sp.SparseConv3d(channels, self.out_channels, 3, indice_key=f"res_{self.out_resolution}"),
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\trellis\modules\sparse\conv\conv_spconv.py", line 11, in __init__
    import spconv.pytorch as spconv
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\spconv\__init__.py", line 15, in <module>
    from . import build as _build
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\spconv\build.py", line 25, in <module>
    from spconv.core import SHUFFLE_SIMT_PARAMS, SHUFFLE_VOLTA_PARAMS, SHUFFLE_TURING_PARAMS, SHUFFLE_AMPERE_PARAMS
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\spconv\core.py", line 15, in <module>
    from cumm.gemm.main import gen_shuffle_params_v2 as gen_shuffle_params, GemmAlgoParams
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\cumm\gemm\main.py", line 29, in <module>
    from cumm import cudasim, dtypes
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\cumm\__init__.py", line 28, in <module>
    pccm.builder.build_pybind([ArrayPtr(), TensorViewBind()],
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\pccm\builder\pybind.py", line 121, in build_pybind
    res = ccimport.ccimport(
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\ccimport\core.py", line 155, in ccimport
    target_filename, no_work = build_simple_ninja(
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\ccimport\buildtools\writer.py", line 1100, in build_simple_ninja
    chunk_or_line = proc.stdout.readline()
  File "D:\ComfyUI-aki-v1.2\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 155: invalid continuation byte

**Comment by smthemex** [comment]
repo路径中有中文或者其他字符?
Are there any Chinese or other characters in the repo path?

**Comment by green21st** [comment]
没有,用3D-pack自动下载模型,加载是也是这个报错.

**Comment by smthemex** [comment]
重新安装cumm 试试
