### ISSUE TITLE
torch.OutOfMemoryError: Allocation on device

### ISSUE THREAD

**Issue by guoyouworld** [smthemex/ComfyUI_TRELLIS#18]
got prompt
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: xformers
E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
using MLP layer as FFN
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\TRELLIS_node.py", line 107, in sampler_main
    glb=image_to_3d(model,img,preprocess_image,covert2video,trial_id,seed,cfg,steps,slat_cfg,slat_steps,mesh_simplify,texture_size,mode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\app.py", line 27, in image_to_3d
    outputs = pipeline.run(
              ^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 286, in run
    cond = self.get_cond([image])
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 164, in get_cond
    cond = self.encode_image(image)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 149, in encode_image
    features = self.models['image_cond_model'](image, is_training=True)['x_prenorm']
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\models\vision_transformer.py", line 325, in forward
    ret = self.forward_features(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\models\vision_transformer.py", line 261, in forward_features
    x = blk(x)
        ^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 254, in forward
    return super().forward(x_or_x_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 113, in forward
    x = x + ffn_residual_func(x)
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 94, in ffn_residual_func
    return self.ls2(self.mlp(self.norm2(x)))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\mlp.py", line 36, in forward
    x = self.act(x)
        ^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\activation.py", line 734, in forward
    return F.gelu(input, approximate=self.approximate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.

**Comment by guoyouworld** [comment]
![Uploading Snipaste_2024-12-31_10-41-30.png…]()

**Comment by smthemex** [comment]
try update ComfyUI_TRELLIS,In the latest version, I have set up Dino's model uninstallation to remove the CPU

**Comment by guoyouworld** [comment]
Yes, I have upgraded the version to the latest[2116cec50eb4981ee8ffc3b53638e9165cadeff9] and it is still the problem


got prompt
pipeline.json: 1.99kB [00:00, 2.28MB/s]
ckpts/ss_dec_conv3d_16l8_fp16.json: 100%|█████████████████████████████████████████████████████| 245/245 [00:00<?, ?B/s]
ss_dec_conv3d_16l8_fp16.safetensors: 100%|██████████████████████████████████████████| 148M/148M [00:19<00:00, 7.76MB/s]
[SPARSE][CONV] spconv algo: auto
ckpts/ss_flow_img_dit_L_16l8_fp16.json: 100%|█████████████████████████████████████████████████| 385/385 [00:00<?, ?B/s]
ss_flow_img_dit_L_16l8_fp16.safetensors: 100%|████████████████████████████████████| 1.13G/1.13G [01:46<00:00, 10.6MB/s]
[ATTENTION] Using backend: flash_attn
(…)s/slat_dec_gs_swin8_B_64l8gs32_fp16.json: 843B [00:00, 828kB/s]
(…)dec_gs_swin8_B_64l8gs32_fp16.safetensors: 100%|██████████████████████████████████| 171M/171M [00:15<00:00, 11.3MB/s](…)ts/slat_dec_rf_swin8_B_64l8r16_fp16.json: 100%|████████████████████████████████████████████| 396/396 [00:00<?, ?B/s](…)_dec_rf_swin8_B_64l8r16_fp16.safetensors: 100%|██████████████████████████████████| 171M/171M [00:15<00:00, 11.1MB/s](…)lat_dec_mesh_swin8_B_64l8m256c_fp16.json: 100%|████████████████████████████████████████████| 372/372 [00:00<?, ?B/s](…)_mesh_swin8_B_64l8m256c_fp16.safetensors: 100%|██████████████████████████████████| 182M/182M [00:21<00:00, 8.56MB/s](…)pts/slat_flow_img_dit_L_64l8p2_fp16.json: 100%|█████████████████████████████████████| 442/442 [00:00<00:00, 451kB/s](…)t_flow_img_dit_L_64l8p2_fp16.safetensors: 100%|████████████████████████████████| 1.20G/1.20G [01:48<00:00, 11.0MB/s]E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
using MLP layer as FFN
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_TRELLIS\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\TRELLIS_node.py", line 114, in sampler_main
    glb=image_to_3d(model,img,preprocess_image,covert2video,trial_id,seed,cfg,steps,slat_cfg,slat_steps,mesh_simplify,texture_size,mode,is_multiimage,gaussians2ply,multiimage_algo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\app.py", line 28, in image_to_3d
    outputs = pipeline.run(
              ^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 290, in run
    cond = self.get_cond([image])
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 168, in get_cond
    cond = self.encode_image(image)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 153, in encode_image
    features = self.models['image_cond_model'](image, is_training=True)['x_prenorm']
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\models\vision_transformer.py", line 325, in forward
    ret = self.forward_features(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\models\vision_transformer.py", line 261, in forward_features
    x = blk(x)
        ^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 254, in forward
    return super().forward(x_or_x_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 113, in forward
    x = x + ffn_residual_func(x)
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\block.py", line 94, in ffn_residual_func
    return self.ls2(self.mlp(self.norm2(x)))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\ComfyUI\custom_nodes\ComfyUI_TRELLIS\facebookresearch/dinov2\dinov2\layers\mlp.py", line 36, in forward
    x = self.act(x)
        ^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_TRELLIS\python_embeded\Lib\site-packages\torch\nn\modules\activation.py", line 734, in forward
    return F.gelu(input, approximate=self.approximate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device


![Snipaste_2024-12-31_15-56-55](https://github.com/user-attachments/assets/917ecb2a-3d77-4e8c-a6bc-084eb30b218a)

![Snipaste_2024-12-31_15-54-33](https://github.com/user-attachments/assets/ecb2f043-9417-4727-bc6c-aff015471611)

**Comment by guoyouworld** [comment]
I used the integration package you provided
2.5.1+cu124

![Snipaste_2024-12-31_16-32-53](https://github.com/user-attachments/assets/7b82e7d8-75d3-4912-829d-f41225c8aa1f)
![Snipaste_2024-12-31_16-35-01](https://github.com/user-attachments/assets/ebc1cec6-046b-4b3a-a045-6d2015c3990b)

**Comment by guoyouworld** [comment]
Sorry, I clicked the wrong button. Turn it back on

**Comment by smthemex** [comment]
check your system path 
![image](https://github.com/user-attachments/assets/577437dd-95dc-4243-9a2e-0c388a014a8c)
or try change another normal input image (not a RGBA mode)

**Comment by wangwangxingao** [comment]
这个是怎么解决的吗?

**Comment by guoyouworld** [comment]
> 这个是怎么解决的吗?

It hasn't been resolved yet. I plan to review the code myself and try to fix this bug
