### ISSUE TITLE
ImportError: DLL load failed while importing bpy: 找不到指定的程序。

### ISSUE THREAD

**Issue by green21st** [smthemex/ComfyUI_TRELLIS#19]
100% done
After remove invisible faces: 7751 vertices, 15475 faces
glb save in D:\ComfyUI-aki-v1.2\output/058bfb69-0342-4332-b5cb-027100d07403_0.glb
Converting glb to obj
Convert Done
!!! Exception during processing !!! DLL load failed while importing bpy: 找不到指定的程序。
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\TRELLIS_node.py", line 148, in sampler_main
    obj2fbx_(i, fbx_path)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TRELLIS\utils.py", line 41, in obj2fbx_
    import bpy
ImportError: DLL load failed while importing bpy: 找不到指定的程序。
已经安装了bpy,但是转fbx时报找不到DLL错误,请问如何解决?

**Comment by smthemex** [comment]
你这个报错是显示没有安装成功，秋叶包安装要带-m  比如 python -m pip install

**Comment by green21st** [comment]
> 你这个报错是显示没有安装成功，秋叶包安装要带-m 比如 python -m pip install

还是不行...
