### ISSUE TITLE
  ModuleNotFoundError: No module named 'torch' when pip install diffoctreerast

### ISSUE THREAD

**Issue by 222222222l** [smthemex/ComfyUI_TRELLIS#7]
Getting requirements to build wheel ...   Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "E:\ComfyUI-aki-v1.3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "E:\ComfyUI-aki-v1.3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "E:\ComfyUI-aki-v1.3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-vupn4ba9\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-vupn4ba9\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
      self.run_setup()
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-vupn4ba9\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-vupn4ba9\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
    File "<string>", line 2, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by smthemex** [comment]
Don't install using pip install  diffoctreerast，need install as below:
git clone --recurse-submodules https://github.com/JeffreyXiang/diffoctreerast.git ./tmp/extensions/diffoctreerast
pip install ./tmp/extensions/diffoctreerast

**Comment by 222222222l** [comment]
> Don't install using pip install diffoctreerast，need install as below: git clone --recurse-submodules https://github.com/JeffreyXiang/diffoctreerast.git ./tmp/extensions/diffoctreerast pip install ./tmp/extensions/diffoctreerast

我就是这样装的，但是明明torch2.51已经装上了，也能正常显示，却报错识别不到toch moudle

**Comment by smthemex** [comment]
你可以试试直接pip install diffoctreerast

**Comment by 222222222l** [comment]
> 你可以试试直接pip install diffoctreerast

已解决，推测是由于网络问题导致依赖没装完整导致的
